steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia-south1-docker.pkg.dev/credible-bay-346209/demo/dockerDemo', '--build-arg=JAR_FILE=build/libs/dockerDemo-0.0.1-SNAPSHOT.jar', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['run', 'gcr.io/$PROJECT_ID/dockerDemo']
images:  ['asia-south1-docker.pkg.dev/credible-bay-346209/demo/dockerDemo']