steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://source.developers.google.com/p/credible-bay-346209/r/github_prasadrpm_dockerdemo']
  
#Gradle build  
- name: 'gradle:7.5.0-jdk11'
  entrypoint: 'gradle'
  args: ['assemble']
   
#Docker Image   
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/credible-bay-346209/dockerdemo','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/credible-bay-346209/dockerdemo']
  
#Compute instance deployment
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute','instances','update-container', 'demoapp', '--zone', 'us-central1-a', '--container-image', 'gcr.io/credible-bay-346209/dockerdemo:latest']
